# Generated by Django 3.0.5 on 2020-04-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECT', '0002_expression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
